apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
  labels:
    client: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:latest
        command: ["/bin/bash"]
        args: ["-c", "apt update && apt install -y net-tools iputils-ping telnet curl && while true; do echo hello; sleep 10;done"]
        volumeMounts:
        - mountPath: "/data"
          name: pvc-storage
      volumes:
        - name: pvc-storage
          persistentVolumeClaim:
            claimName: nfs
