---
# Database credentials
apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
type: Opaque
data:
    mysql-root-username: cm9vdA==
    mysql-root-password: cm9vdA==

---
# Database URL config map
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  database_url: mysql-service

---
# MYSQL server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        args:
        - "--default-authentication-plugin=mysql_native_password"
        - "--datadir=/data/mysql"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-username
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"

---
# MYSQL service port 3306
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
# Application port 8080
apiVersion: apps/v1
kind: Deployment
metadata:
  name: names-application
  labels:
    app: names-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: names-application
  template:
    metadata:
      labels:
        app: names-application
    spec:
      containers:
      - name: names-application
        image: gathecageorge/node-names-application:latest
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-username
        - name: DATABASE_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: DATABASE_HOST
          valueFrom: 
            configMapKeyRef:
              name: mysql-configmap
              key: database_url
        - name: PORT
          value: "8080" 
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

---
# Application service 8080
apiVersion: v1
kind: Service
metadata:
  name: names-application-service
spec:
  selector:
    app: names-application
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
