apiVersion: apps/v1
kind: Deployment
metadata:
  name: lighthouse-deployment
  labels:
    app: testnet
    name: lighthouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testnet
      name: lighthouse
  template:
    metadata:
      labels:
        app: testnet
        name: lighthouse
    spec:
      volumes:
        - name: custom-config-data-claim
          persistentVolumeClaim:
            claimName: custom-config-data-claim
      containers:
      - name: lighthouse-beacon
        image: sigp/lighthouse:latest
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        args:
        - "lighthouse"
        - "--debug-level=debug"
        - "--datadir=/beacondata"
        - "--testnet-dir=/custom_config_data"
        - "bn"
        - "--disable-enr-auto-update"
        - "--enr-tcp-port=9000"
        - "--enr-udp-port=9000"
        - "--port=9000"
        - "--discovery-port=9000"
        - "--http"
        - "--http-address=0.0.0.0"
        - "--http-port=4000"
        - "--metrics"
        - "--metrics-address=0.0.0.0"
        - "--metrics-port=8000"
        - "--listen-address=0.0.0.0"
        - "--graffiti=geth-lighthouse"
        - "--target-peers=25"
        - "--eth1"
        - "--enr-address=$(POD_IP)"
        - "--boot-nodes=enr:-Iq4QJ_uz4Bg0mOrI6TR9kCOHPOsblm7ZXmSfbMkyD_neDVaYoR7JeoO2oTIQ6mMENEd1f3hvZEIitsu00yV0YJ8GkOGAYOg6tsJgmlkgnY0gmlwhAoCADGJc2VjcDI1NmsxoQPJ0lHBeXr6cdq-_RN9q4QKqxFnHPdUXMeOeY1MaNsEU4N1ZHCCIyk"
        - "--eth1-endpoints=http://173.230.158.103:8545"
        volumeMounts:
          - mountPath: "/custom_config_data"
            name: custom-config-data-claim
        ports:
        - containerPort: 9000
          name: http
        - containerPort: 8000
          name: metrics
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
