apiVersion: apps/v1
kind: Deployment
metadata:
  name: nimbus-deployment
  labels:
    app: testnet
    name: nimbus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testnet
      name: nimbus
  template:
    metadata:
      labels:
        app: testnet
        name: nimbus
    spec:
      volumes:
        - name: custom-config-data-claim
          persistentVolumeClaim:
            claimName: custom-config-data-claim
      containers:
      - name: nimbus-beacon
        image: statusim/nimbus-eth2:multiarch-latest
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        args:
        # - "--data-dir=/beacondata"
        - "--non-interactive"
        - "--status-bar=false"
        - "--tcp-port=9000"
        - "--udp-port=9000"
        - "--max-peers=25"
        - "--graffiti=geth-nimbus"
        - "--log-level=debug"
        - "--rest"
        - "--rest-port=4000"
        - "--rest-address=0.0.0.0"
        - "--enr-auto-update=false"
        - "--doppelganger-detection=off"
        - "--metrics"
        - "--metrics-port=8000"
        - "--metrics-address=0.0.0.0"
        - "--listen-address=0.0.0.0"
        - "--validator-monitor-auto"
        - "--dump:on"
        # - "--validators-dir=/validatordata/keys"
        # - "--secrets-dir=/validatordata/secrets"
        - "--nat=extip:$(POD_IP)"
        - "--network=/custom_config_data"
        - "--bootstrap-node=enr:-Iq4QJ_uz4Bg0mOrI6TR9kCOHPOsblm7ZXmSfbMkyD_neDVaYoR7JeoO2oTIQ6mMENEd1f3hvZEIitsu00yV0YJ8GkOGAYOg6tsJgmlkgnY0gmlwhAoCADGJc2VjcDI1NmsxoQPJ0lHBeXr6cdq-_RN9q4QKqxFnHPdUXMeOeY1MaNsEU4N1ZHCCIyk"
        - "--web3-url=http://173.230.158.103:8545"
        volumeMounts:
          - mountPath: "/custom_config_data"
            name: custom-config-data-claim
        ports:
        - containerPort: 9000
          name: http
        - containerPort: 8000
          name: metrics
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
