apiVersion: apps/v1
kind: Deployment
metadata:
  name: prysm-deployment
  labels:
    app: testnet
    name: prysm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testnet
      name: prysm
  template:
    metadata:
      labels:
        app: testnet
        name: prysm
    spec:
      containers:
      - name: prysm-beacon
        image: prysmaticlabs/prysm-beacon-chain:latest
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        args:
        - "--accept-terms-of-use=true"
        - "--datadir=/beacondata"
        - "--verbosity=debug"
        - "--min-sync-peers=1"
        - "--pprof"
        - "--p2p-max-peers=25"
        - "--p2p-udp-port=9000"
        - "--p2p-tcp-port=9000"
        - "--monitoring-host=0.0.0.0"
        - "--monitoring-port=8000"
        - "--rpc-host=0.0.0.0"
        - "--rpc-port=4001"
        - "--grpc-gateway-host=0.0.0.0"
        - "--grpc-gateway-port=4000"
        - "--enable-debug-rpc-endpoints"
        - "--p2p-host-ip=$(POD_IP)"
        - "--bootstrap-node=enr:-Iq4QJ_uz4Bg0mOrI6TR9kCOHPOsblm7ZXmSfbMkyD_neDVaYoR7JeoO2oTIQ6mMENEd1f3hvZEIitsu00yV0YJ8GkOGAYOg6tsJgmlkgnY0gmlwhAoCADGJc2VjcDI1NmsxoQPJ0lHBeXr6cdq-_RN9q4QKqxFnHPdUXMeOeY1MaNsEU4N1ZHCCIyk"
        - "--execution-endpoint=http://173.230.158.103:8545"
        - "--genesis-state=/data/custom_config_data/genesis.ssz"
        - "--chain-config-file=/data/custom_config_data/config.yaml"
        ports:
        - containerPort: 9000
          name: http
        - containerPort: 8000
          name: metrics
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
