apiVersion: apps/v1
kind: Deployment
metadata:
  name: teku-deployment
  labels:
    app: testnet
    name: teku
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testnet
      name: teku
  template:
    metadata:
      labels:
        app: testnet
        name: teku
    spec:
      volumes:
        - name: custom-config-data-claim
          persistentVolumeClaim:
            claimName: custom-config-data-claim
      containers:
      - name: teku-beacon
        image: consensys/teku:latest
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        args:
        # - "--data-path=/beacondata"
        - "--data-storage-mode=PRUNE"
        - "--p2p-enabled=true"
        - "--p2p-port=9000"
        - "--p2p-advertised-port=9000"
        - "--logging=debug"
        - "--log-destination=CONSOLE"
        - "--log-file=/beacondata/log_outputs"
        - "--p2p-peer-upper-bound=25"
        - "--metrics-enabled=true"
        - "--metrics-interface=0.0.0.0"
        - "--metrics-port=8000"
        - "--p2p-discovery-enabled=true"
        - "--p2p-peer-lower-bound=1"
        - "--rest-api-enabled=true"
        - "--rest-api-docs-enabled=true"
        - "--rest-api-interface=0.0.0.0"
        - "--rest-api-port=4000"
        - "--metrics-host-allowlist=*"
        - "--rest-api-host-allowlist=*"
        - "--p2p-advertised-ip=$(POD_IP)"
        - "--p2p-discovery-bootnodes=enr:-Iq4QJ_uz4Bg0mOrI6TR9kCOHPOsblm7ZXmSfbMkyD_neDVaYoR7JeoO2oTIQ6mMENEd1f3hvZEIitsu00yV0YJ8GkOGAYOg6tsJgmlkgnY0gmlwhAoCADGJc2VjcDI1NmsxoQPJ0lHBeXr6cdq-_RN9q4QKqxFnHPdUXMeOeY1MaNsEU4N1ZHCCIyk"
        - "--network=/custom_config_data/config.yaml"
        - "--initial-state=/custom_config_data/genesis.ssz"
        - "--ee-endpoint=http://173.230.158.103:8545"
        - "--eth1-endpoint=http://173.230.158.103:8545"
        volumeMounts:
          - mountPath: "/custom_config_data"
            name: custom-config-data-claim
        ports:
        - containerPort: 9000
          name: http
        - containerPort: 8000
          name: metrics
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
