---
# Mount NFS server to volume that is Read/Writtable many
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # todo change IP to nfs service nodeport IP
    server: 10.128.3.245
    path: "/"

---
# Create clain of volume with Read/Writtable many
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
